apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  labels:
    app: notification-service
type: Opaque
data:
  # Valeurs encodees en base64 (echo -n 'valeur' | base64)
  MYSQL_ROOT_PASSWORD: "UkVQTEFDRV9NRQ=="
  MYSQL_PASSWORD: "UkVQTEFDRV9NRQ=="
  JWT_SECRET: "UkVQTEFDRV9NRQ=="
  SPRING_MAIL_USERNAME: "UkVQTEFDRV9NRQ=="
  SPRING_MAIL_PASSWORD: "UkVQTEFDRV9NRQ=="
  TWILIO_ACCOUNT_SID: "UkVQTEFDRV9NRQ=="
  TWILIO_AUTH_TOKEN: "UkVQTEFDRV9NRQ=="
  TWILIO_FROM_PHONE: "UkVQTEFDRV9NRQ=="
